### ISSUE TITLE
Reconnecting on AWS Lambda

### ISSUE THREAD

**Issue by janmeier** [nats-io/node-nats#171] opened 2017-10-25 15:21 UTC
We are seeing intermittent issue on AWS lambda, where the client is failing to publish messages to NATS within five seconds (which is the timeout we have for all NATS clients in our infrastructure). This is only a problem on lambda.

The client is initiated with default options, so as far as I can see it should attempt to reconnect after two seconds.

I have a feeling that the client is not reconnecting because `close` is not being emitted on the stream when the container i frozen and then thawed afterwards. I'm not entirely sure how thawing containers works on AWS lambda, but I have a feeling that network interfaces might be re-attached when the container thaws, requiring a reconnect.

Do you have any insights about running NATS clients on AWS Lambda in general?

I've tried calling the internal `reconnect` method on the client at the beginning of each lambda invocation which seemed to help the problem slightly, but did not alleviate it completely. Our current solution is to create a new NATS client for each lambda invocation.

**Comment by ColinSullivan1** [comment] 2017-10-25 15:54
@janmeier , I agree that freeze/thaw here could be a culprit.  Would you have NATS server logs from the time this happens?  In addition to your suspicions around network interface bindings, I can also imagine a case where the server disconnects the client due to inactivity, but after the client is thawed the clients doesn't reflect that connection state.  @aricart - any additional comments?

**Comment by aricart** [comment] 2017-10-25 16:33
@janmeier the default reconnectTimeWait is 2 seconds, maxReconnectAttempts is 10. I think for sure you want to set maxReconnectsAttempts to -1. Now lets try to break it down.

First thing, `reconnect()` is private API, so your mileage will vary.

The main problem you are trying to solve is to determine whether you are connected to the server or not. I made this small gist to illustrate one possible way https://gist.github.com/aricart/2796171f295fd4bdf59d57a5f2d383e9

The other things to verify is whether you are providing a callback for `context.done()` on your lambda. If you are not, it is possible that they are freezing at the wrong time. 

Your flow likely needs to verify the connection/reconnect as shown.
Then process your logic, publishing any messages etc.
Calling `flush` on NATS with a callback that invokes `context.done()`.

**Comment by janmeier** [comment] 2017-10-25 21:06
I looked at the nats logs, but didn't find anything interesting (nothing logged at all around the time of the issues - Should I increase the log level? - It's at INF currently).

I've managed to semi-reliably reproduce the issue so I will share what I have so far (still way to much code for it to be meaningfull to share). I added the debug code from the gist to my code.

I've attached some cleaned up cloudwatch logs here https://gist.github.com/janmeier/6c3b6cb007a5750f9840d23b55ea1049

The gist (the-he) of the gist is:

* Initial connect at 20:26.
* Client stays connected until 20:35. In this period the container receives requests at least once per minute.
* Then there is a five minute gap where no requests are coming in (don't ask me why - I was still sending requests, but they must have been routed to other containers).
* From 20:40 until 20:45 (where i stopped testing) the client reports not connected 

There were no logs of either `disconnected` or `close` being emitted.

I will try set max reconnect attempts tomorrow, but since the client remains in a not connected state for several minutes I suspect that the client does not actually notice that it has lost connecting, and is therefore not trying to reconnect.

**Comment by aricart** [comment] 2017-10-26 13:40
> There were no logs of either disconnected or close being emitted.

@janmeier Sorry the final gist got a message refactored, and I inadvertently renamed the event from 'disconnect' to 'disconnected' on the sample. I have updated it. I also added a 'reconnecting' handler so you can see when the library attempts to reconnect.

Note that the `close` events are only emitted if you directly call `close()`, `reconnect`option is set to `false` or you reached `maxReconnectAttempts` options.

**Comment by ColinSullivan1** [comment] 2017-10-26 16:07
@janmeier , Thanks for the additional info.  Regarding NATS server logs, you'll want to can increase the log level with the `-D` parameter.  That should give us the connection related information we need, If you have lower throughput `-DV` is better and will give additional information, but will be extremely verbose (it will trace every message).

**Comment by janmeier** [comment] 2017-10-27 07:19
Here's a test case where I've managed to replicate the issue 

```js
import {connect, createInbox} from 'nats';
import Promise from 'bluebird';

let nc = connect({
	servers: process.env.NATS_HOSTS.split(',')
});


nc.publish = Promise.promisify(nc.publish, { context: nc });

nc.on('error', function(e) {
    console.error(e);
    process.exit();
});

nc.on('disconnect', () => console.log('disconnected'));

nc.on('reconnecting', () => console.log('reconnecting'));

nc.on('close', () => console.log('close'));

nc.on('connect', () => console.log('initial connect'));

// this here for testing by stopping the server/ctrl-Z etc.
setInterval(testConnection, 5000);

// test the connection - by flushing and expecting the flushing
// to be done before some external timeout.
var timeout = null;
function testConnection() {
	console.log('testing connection')
    timeout = setTimeout(function() {
        console.log('not connected');
        // re-establish your connection
        timeout = null;
    }, 500);
    nc.flush(function() {
        if(timeout) {
            console.log('connected');
            clearTimeout(timeout);
            timeout = null;
        }
    });
}

module.exports = {
	handle: async function (event, context) {
		try {
			console.log('sending request');
			await nc.publish('foo.bar', Math.random().toString());
			context.succeed({
				statusCode: 200
			});
		} catch (error) {
			context.succeed({
				statusCode: 500,
				text: error.message
			});
		}
	}
}
```

Invoking this function with a five minute interval I get the following output:
```
{
    "statusCode": 200
}
--------------------------------------------------------------------
START RequestId: 9b52bca3-bae4-11e7-ad1f-ffb3f3a30b6c Version: $LATEST
2017-10-27 09:01:08.977 (+02:00)	9b52bca3-bae4-11e7-ad1f-ffb3f3a30b6c	sending request
2017-10-27 09:01:09.118 (+02:00)	9b52bca3-bae4-11e7-ad1f-ffb3f3a30b6c	initial connect
END RequestId: 9b52bca3-bae4-11e7-ad1f-ffb3f3a30b6c
REPORT RequestId: 9b52bca3-bae4-11e7-ad1f-ffb3f3a30b6c	Duration: 214.69 ms	Billed Duration: 300 ms 	Memory Size: 128 MB	Max Memory Used: 23 MB	




{
    "statusCode": 200
}
--------------------------------------------------------------------
START RequestId: 504add57-bae5-11e7-84c3-2fb65e141cd3 Version: $LATEST
2017-10-27 09:06:11.580 (+02:00)	9b52bca3-bae4-11e7-ad1f-ffb3f3a30b6c	testing connection
2017-10-27 09:06:11.677 (+02:00)	9b52bca3-bae4-11e7-ad1f-ffb3f3a30b6c	connected
2017-10-27 09:06:11.678 (+02:00)	504add57-bae5-11e7-84c3-2fb65e141cd3	sending request
END RequestId: 504add57-bae5-11e7-84c3-2fb65e141cd3
REPORT RequestId: 504add57-bae5-11e7-84c3-2fb65e141cd3	Duration: 172.18 ms	Billed Duration: 200 ms 	Memory Size: 128 MB	Max Memory Used: 24 MB	


{
    "errorMessage": "2017-10-27T07:12:14.574Z 04dc9a2a-bae6-11e7-9999-6b03f875ab42 Task timed out after 60.05 seconds"
}
--------------------------------------------------------------------
START RequestId: 04dc9a2a-bae6-11e7-9999-6b03f875ab42 Version: $LATEST
2017-10-27 09:11:14.524 (+02:00)	504add57-bae5-11e7-84c3-2fb65e141cd3	testing connection
2017-10-27 09:11:14.536 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	sending request
2017-10-27 09:11:14.576 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	disconnected
2017-10-27 09:11:15.025 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	not connected
2017-10-27 09:11:19.529 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	testing connection
2017-10-27 09:11:19.530 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	connected
2017-10-27 09:11:24.534 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	testing connection
2017-10-27 09:11:24.534 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	connected
2017-10-27 09:11:29.539 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	testing connection
2017-10-27 09:11:29.539 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	connected
2017-10-27 09:11:34.544 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	testing connection
2017-10-27 09:11:34.545 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	connected
2017-10-27 09:11:39.550 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	testing connection
2017-10-27 09:11:39.551 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	connected
2017-10-27 09:11:44.555 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	testing connection
2017-10-27 09:11:44.555 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	connected
2017-10-27 09:11:49.560 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	testing connection
2017-10-27 09:11:49.561 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	connected
2017-10-27 09:11:54.566 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	testing connection
2017-10-27 09:11:54.567 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	connected
2017-10-27 09:11:59.566 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	testing connection
2017-10-27 09:11:59.567 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	connected
2017-10-27 09:12:04.570 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	testing connection
2017-10-27 09:12:04.571 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	connected
2017-10-27 09:12:09.575 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	testing connection
2017-10-27 09:12:09.575 (+02:00)	04dc9a2a-bae6-11e7-9999-6b03f875ab42	connected
END RequestId: 04dc9a2a-bae6-11e7-9999-6b03f875ab42
REPORT RequestId: 04dc9a2a-bae6-11e7-9999-6b03f875ab42	Duration: 60049.27 ms	Billed Duration: 60000 ms 	Memory Size: 128 MB	Max Memory Used: 24 MB	

2017-10-27T07:12:14.574Z 04dc9a2a-bae6-11e7-9999-6b03f875ab42 Task timed out after 60.05 seconds
```

The first two attempts work fine, but on the third the connection has been lost. Calling flush actually makes nats create a new connection, but the publish request seems to be sent on the old connection, and is not resent:
```
09:11:14.524 testing connection
09:11:14.536 sending request
09:11:14.576 disconnected
09:11:15.025 not connected
09:11:19.529 testing connection
09:11:19.530 connected
```

I could fix this by calling flush and waiting for the callback to be called or the disconnected event to be emitted before sending of my publish request, but I feel like this should be handled internally in the client.

**Comment by janmeier** [comment] 2017-10-27 08:11
@ColinSullivan1 I tried enabling debug information, but given that this is a production server, and that it's (to my knowledge) not possible to determine the IP address of a lambda function I didn't get any useful info.
I will try to find the time to set up a separate NATS instance to test this sometime next week

**Comment by aricart** [comment] 2017-10-27 19:27
@janmeier few things:
- Remember that NATS is not reliable messaging. If you want to know that your message was acted on, you likely should be doing a Request/Reply for the operation or switch to NATS streaming.
- I am thinking the issue here is that the AWS is messing with the vm after the message has been queued up, but before the `socket.write` happens. NATS clients typically don't recover from that operation, as the pending message buffer is cleared at that point (similarly the if the server receives a partial message, it would just drop it).
- Since you have a condition where the socket is not reliable, I would suggest the following:
 
1. Connect when your lambda operation starts, `publish`, and `flush `while performing ensuring that your lambda `context.done` is called after the final `flush` and `close` is invoked. This may be viable if you are not getting invoked at a great frequency.
1. Another possibility your lambda operation starts, you can also try doing a flush with a callback that performs your `publish` and also having a `flush` callback, which then invokes your `context.done`.

**Comment by janmeier** [comment] 2017-11-19 14:59
I've played around with this quite a lot, and it's definitely working better, but we are still seeming a small portion of timeouts. However, I have not been able to create a small test-case that can reliably reproduce this, so I will try to relay my findings.

> Another possibility your lambda operation starts, you can also try doing a flush with a callback that performs your publish and also having a flush callback, which then invokes your context.done.

I implemented a flush operation at the start of each lambda invocation, and that seems to have helped a great deal to figure out if we are still connected to NATS.

However, we are still seeing intermittent timeouts where the publish callback may take up to 10 seconds to be called (even after making sure that we are connected to NATS). I perused over the code, and it seems that the publish callback is not called before the server responds with a `PONG` (and only one callback is called for each PONG). Are there cases where the server may not respond to a `PING` immediately? For example if we are sending a lot of other requests over the wire?

 Looking at the [protocol demo](https://nats.io/documentation/internals/nats-protocol-demo/) the server responds with `OK` to acknowledge that a message has been published - Is there any reason why the OK message is ignored?

**Comment by janmeier** [comment] 2017-11-19 14:59
By the way - Thank you for working with me on this - Really appreciated!

**Comment by aricart** [comment] 2017-11-20 15:46
@janmeier you are welcomed.

There's a slight difference. The `+OK` is returned for a successful operation. The problem is that from that we cannot determine which operation succeeded. In the case of the callbacks, they are registered with a specific `PING` sent on the flush. When the matching `PONG` is returned, the callback is invoked.

BTW - I think this issue is also related to #174. It is fixed in the master branch, but not yet available. I am wondering if the version in master will ameliorate the issue with zero code from your side.

**Comment by ColinSullivan1** [comment] 2017-12-12 21:05
@janmeier , just following up...  Would you mind testing if #174 in the master branch fixes this issue for you?

**Comment by ColinSullivan1** [comment] 2018-01-13 00:18
Closing due to inactivity.  Please re-open if this continues to be an issue.

**Closed by ColinSullivan1** 2018-01-13 00:18 UTC
