### ISSUE TITLE
JSON Parse Error

### ISSUE THREAD

**Issue by ahallock** [nats-io/node-nats#17] opened 2015-08-30 03:17 UTC
I have a JSON structure with a text field (which also happens to be JSON in this failure case), and intermittently receive a JSON parse error when parsing that field. I was able to reproduce (sometimes) using the following:

https://gist.github.com/ahallock/38afc33f1f6d16064d5c

Versions:
node-nats 0.4.0
https://hub.docker.com/r/apcera/gnatsd/ (latest)
iojs 1.8.4

When the parsing error occurs, the incoming message appears "garbled" with unknown characters:
��&��I�,��!�f�1�7�|)�:�|))]&��)]

I'll dig into this more as well (nats is awesome!)

**Comment by derekcollison** [comment] 2015-08-30 06:28
Try node-nats 0.4.2 and see if you can repeat it with the latest release..

I will take a look as well, thanks for the report.

**Comment by derekcollison** [comment] 2015-08-30 06:29
Also latest version of gnatsd under the docker repo is compiled with 1.5 which had some anomalies. The official releases for gnatsd 0.6.6 were reverted to being compiled with 1.4.2, but I left the docker images as is for now, 1.5.1 is supposed to be out soon.

**Comment by derekcollison** [comment] 2015-08-30 06:32
iojs is now on version 3.2.0, so that is another variable.

**Comment by ahallock** [comment] 2015-08-30 15:15
I tried using:
iojs 3.2
gnatsd 0.6.6
node-nats 0.4.2

The problem persists, but appears to be less frequent. Could it be something with the large number of `\` in the JSON string?

**Comment by derekcollison** [comment] 2015-08-30 15:23
node v0.12.7 same issue?

**Comment by derekcollison** [comment] 2015-08-30 15:23
Unclear, but I will take a look. Thanks again for the heads up..

**Comment by ahallock** [comment] 2015-08-30 16:09
Happens on node v0.12.7 as well. Seems to longer strings causing the issue, not `\`. Threw together a rough test:
https://gist.github.com/ahallock/38afc33f1f6d16064d5c#file-test2-js

**Comment by derekcollison** [comment] 2015-08-31 03:45
Thanks, will take a look in next day or so.. Appreciate the details.

**Comment by kozlovic** [comment] 2015-08-31 17:01
Looks like test2.js is incorrect. You should do buffer.write('a', i); instead. Otherwise, you just set one character and convert it to a string that does not have an ending. If you were to print the reply before publishing it (in subscribe()), you would see that you are sending random bytes...

I can't make test.js to fail on my system though.

**Comment by ahallock** [comment] 2015-08-31 17:18
@kozlovic Even with `buffer.write('a', i)` I'm still receiving the same error. What is your environment?

**Comment by kozlovic** [comment] 2015-08-31 17:47
Node: v0.12.7
gnatsd: 0.6.6
mac book pro/Yosemite

What error are you receiving? Is it in the client with say "Bad length", or other errors, or in gnatsd? Have you tried running gnatsd with the command line parameters "-DV" and check that the sizes are consistent (last filed in [MSG and [PUB should be 10000).

**Comment by ahallock** [comment] 2015-08-31 17:50
The "Bad length" error. Sometimes it will complete without any errors, sometimes the length difference is 20 or so. I'll try running gnatsd with "-DV"

**Comment by derekcollison** [comment] 2015-09-02 15:35
I am going to take a look today. I will check to make sure its valid JSON (most likely is fine) and also if compiling the current server with go1.4.2 vs go1.5 makes a difference. Again, thanks for the patience..

**Comment by derekcollison** [comment] 2015-09-03 00:03
Some updates, I do not believe its the gnatsd code base, I dissected it fairly well. Its something in the Node client. It is hard to reproduce but I have seen it have the wrong length. Stay tuned.

**Comment by derekcollison** [comment] 2015-09-03 18:08
ok I have tracked it down, it's a bug in the Node.js client. Will checkin fix in a short bit, have one more issue I want to address then will do a release. Feel free to look at head to test that it works for you while you wait for it to land in npm, but I am sure this is the issue. Reproduced with a modified version of your test. 

Thanks..

**Comment by derekcollison** [comment] 2015-09-03 18:14
Fix is in master if you want to test.

**Closed** 2015-09-03 18:14 UTC

**Comment by ahallock** [comment] 2015-09-03 18:33
Will check shortly -- thanks for digging into this.

**Comment by derekcollison** [comment] 2015-09-03 18:35
Thanks for the report.
